apiVersion: v1
kind: ConfigMap
metadata:
  name: kepler
  namespace: kepler
  labels:
    app.kubernetes.io/name: kepler
    app.kubernetes.io/part-of: kepler
data:
  config.yaml: |
    log:
      level: debug
      format: text
    host:
      sysfs: /host/sys
      procfs: /host/proc
    monitor:
      interval: 5s
      staleness: 500ms
      maxTerminated: 100
      minTerminatedEnergyThreshold: 10
    rapl:
      zones: []
    exporter:
      stdout:
        enabled: false
      prometheus:
        enabled: true
        debugCollectors:
          - go
    web:
      configFile: ""
      listenAddresses:
        - ":28282"
    debug:
      pprof:
        enabled: false
    kube:
      enabled: false
      config: ""
      nodeName: ""
    dev:
      fake-cpu-meter:
        enabled: false
        zones: []
    # EXPERIMENTAL FEATURES - These features are experimental and may be unstable
    # and are disabled by default
    experimental:
      platform:
        redfish:
          enabled: false  # Enable experimental Redfish BMC power monitoring
          configFile: "/etc/kepler/redfish.yaml"  # Path to Redfish BMC configuration file
          nodeName: ""  # Node name to use (overrides Kubernetes node name and hostname fallback)
          httpTimeout: 5s  # HTTP client timeout for BMC requests (default: 5s)
