apiVersion: v1
kind: Service
metadata:
  name: kepler
  namespace: kepler
  labels:
    app.kubernetes.io/name: kepler
    app.kubernetes.io/part-of: kepler
spec:
  type: NodePort
  ports:
    - name: http
      port: 28282
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: kepler
    app.kubernetes.io/part-of: kepler
